
sudo: required
services:
  - docker
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python main.py >> log.txt 2>&1 &
  - pytest
after_success:
  - sh .travis/deploy_dockerhub.sh
#  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh