# Use an official Python runtime as an image
FROM python:3.7-alpine

# Sets the working directory for following COPY and CMD instructions
# Notice we haven’t created a directory by this name - this
# instruction creates a directory with this name if it doesn’t exist
COPY . /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install pytest pytest-flask requests

# Run python main.py when the container launches
CMD ["pytest"]