openapi: 3.0.0
info:
  title: EnsemblSearchGeneApi
  description: RESTful API that allows user to search for a gene in Ensembl Database
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/MariumAli/EnsemblSearchGeneRestApi/1.0.0
  description: SwaggerHub API Auto Mocking
#- url: http://localhost:5000/
#  description: Testing server
- url: https://ensembl-search-gene-api.herokuapp.com/
  description: Heroku Deployment server
paths:
  /:
    get:
      summary: Welcomes to search gene API.
      responses:
        200:
          description: Connection successfull.
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to search gene API

  /{name}:
    get:
      summary: Fetch genes from database with names having prefix 'name'.
      description: Fetch all genes that starts with 'name' input
      operationId: genes.get
      parameters:
      - name: name
        in: path
        description: The mandatory name field for which will act as a prefix in searching
          databse.
        required: true
        style: simple
        explode: false
        schema:
          minLength: 3
          type: string
      responses:
        200:
          description: Returns array of matched genes from db.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genes'
        400:
          $ref: '#/components/schemas/IllegalInput'
      security:
      - OAuth2:
        - read

    post:
      summary: Invalid Request.
      operationId: genes.post
      parameters:
      - name: name
        in: path
        required: true
        schema:
          minLength: 3
          type: string
      responses:
        405:
          $ref: '#/components/schemas/InvalidRequest'
    put:
      summary: Invalid Request.
      operationId: genes.put
      parameters:
      - name: name
        in: path
        required: true
        schema:
          minLength: 3
          type: string
      responses:
        405:
          $ref: '#/components/schemas/InvalidRequest'
    patch:
      summary: Invalid Request.
      operationId: genes.patch
      parameters:
      - name: name
        in: path
        required: true
        schema:
          minLength: 3
          type: string
      responses:
        405:
          $ref: '#/components/schemas/InvalidRequest'
    delete:
      summary: Invalid Request.
      operationId: genes.delete
      parameters:
      - name: name
        in: path
        required: true
        schema:
          minLength: 3
          type: string
      responses:
        405:
          $ref: '#/components/schemas/InvalidRequest'

  /{name}/{species}:
    get:
      summary: Fetch genes from database.
      description: Fetch all genes that starts with 'name' input and belongs to species
        specified by 'species' input
      operationId: genes.getWithSpecies
      parameters:
      - name: name
        in: path
        description: The mandatory name field for which will act as a prefix in searching
          databse.
        required: true
        style: simple
        explode: false
        schema:
          minLength: 3
          type: string
      - name: species
        in: path
        description: The optional species field to which gene belongs.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: Returns array of matched genes from db.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genes'
        400:
          $ref: '#/components/schemas/IllegalInput'
        405:
          $ref: '#/components/schemas/InvalidRequest'
      security:
      - OAuth2:
        - read
components:
  schemas:
    Genes:
      type: array
      items:
        $ref: '#/components/schemas/GenesFormat'
    GenesFormat:
      type: object
      properties:
        id:
          type: string
          example: ENSBBBG00000011471
        name:
          type: string
          example: TBRG1
        species:
          type: string
          example: bison_bison_bison
    IllegalInput:
      description: Bad request. Gene name must be a string of minimum length 3.
    InvalidRequest:
      description: Invalid Request. Only GET method is allowed.
